# Generated by Django 3.1.8 on 2021-06-01 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=10, verbose_name='创建人')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated_by', models.CharField(max_length=10, verbose_name='修改人')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
                ('name', models.CharField(max_length=128, verbose_name='小说名称')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('introduction', models.CharField(max_length=512, verbose_name='简介')),
                ('favorites_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '连载'), (2, '完本')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '小说管理',
                'verbose_name_plural': '小说管理',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=10, verbose_name='创建人')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated_by', models.CharField(max_length=10, verbose_name='修改人')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=10, verbose_name='创建人')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated_by', models.CharField(max_length=10, verbose_name='修改人')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
                ('name', models.CharField(max_length=64, verbose_name='章节名称')),
                ('content_url', models.CharField(max_length=64, verbose_name='章节路径')),
                ('index', models.IntegerField(default=0, verbose_name='章节索引')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
                'ordering': ('book_id',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='book',
            name='lasted_chapter',
            field=models.ForeignKey(db_column='lasted_chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.chapter', verbose_name='最新章节'),
        ),
    ]
