# Generated by Django 3.1.8 on 2021-05-31 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=10, verbose_name='创建人')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('updated_by', models.CharField(max_length=10, verbose_name='修改人')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
                ('account', models.CharField(max_length=32, verbose_name='账户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('qq', models.CharField(max_length=32, verbose_name='qq')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='收藏时间')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='收藏书籍')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='收藏人')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
            },
        ),
    ]
